export const presets = {
  styles: [
    "cinematic",
    "photorealistic",
    "documentary",
    "anime",
    "3d render",
    "pixel art",
    "noir",
    "surreal",
    "vintage",
    "hyperreal",
    "dreamy",
    "gritty",
  ],
  shotTypes: [
    "extreme close-up",
    "close-up",
    "medium",
    "cowboy",
    "wide",
    "establishing",
    "aerial",
    " pov",
    "over-the-shoulder",
    "tracking",
  ],
  lenses: ["18mm", "24mm", "28mm", "35mm", "50mm", "85mm"],
  cameraMovements: [
    "static",
    "handheld",
    "slow pan",
    "slow tilt",
    "slow dolly",
    "push in",
    "pull back",
    "orbit",
    "crane",
    "tracking",
  ],
  aspectRatios: ["16:9", "9:16", "1:1", "2.39:1"],
  resolutions: ["720p", "1080p", "4k"],
  lighting: [
    "soft",
    "hard",
    "rim light",
    "backlit",
    "volumetric",
    "bioluminescent glow",
    "neon",
    "golden hour",
    "moonlit",
  ],
  colorGrades: [
    "teal and orange",
    "bleach bypass",
    "high contrast",
    "matte",
    "cool blue",
    "warm amber",
  ],
  moods: [
    "mysterious",
    "awe",
    "tension",
    "romance",
    "melancholic",
    "uplifting",
    "epic",
    "whimsical",
  ],
  timesOfDay: ["dawn", "morning", "noon", "golden hour", "dusk", "night"],
  weather: ["clear", "fog", "rain", "snow", "stormy"],
};
